// Super-admin dashboard API. Hits lumid_identity's /api/v1/admin/*
// surface introduced in P3.1. Same-origin from lum.id, so the
// lm_session cookie + the SuperAdminGuard at the route level is the
// only auth — no scoped bearer needed.

import apiClient from './client';
import type { DataResponse } from './types';

// ---- /admin/auth-stats ----

export interface AuthStatsBucket {
	total: number;
	failed: number;
}

export interface AuthStatsHourly {
	hour: string;
	total: number;
	failed: number;
}

export interface AuthStats {
	window: string;
	generated_at: string;
	login: AuthStatsBucket;
	oauth: AuthStatsBucket;
	hourly: AuthStatsHourly[];
}

export async function fetchAuthStats(): Promise<AuthStats> {
	const r = await apiClient.get<DataResponse<AuthStats>>('/api/v1/admin/auth-stats');
	return r.data.data;
}

// ---- /admin/qa-summary ----

export interface QASummary {
	strategies: { total: number; active: number };
	competitions: { total: number; ongoing: number; upcoming: number };
	trades_24h: { count: number };
	generated_at: string;
}

export async function fetchQASummary(): Promise<QASummary> {
	const r = await apiClient.get<DataResponse<QASummary>>('/api/v1/admin/qa-summary');
	return r.data.data;
}

// ---- /admin/cert-expiry ----

export interface CertRow {
	domain: string;
	expires_at: string;
	days_left: number;
}

export interface CertExpiry {
	certificates: CertRow[];
	checked_at: string;
}

export async function fetchCertExpiry(): Promise<CertExpiry> {
	const r = await apiClient.get<DataResponse<CertExpiry>>('/api/v1/admin/cert-expiry');
	return r.data.data;
}

// ---- /admin/backup-status ----

export interface BackupJob {
	job: string;
	last_run: string;
	age_hours: number;
	healthy: boolean;
}

export interface BackupStatus {
	jobs: BackupJob[];
	verify: { healthy: boolean; last_run?: string };
	checked_at: string;
}

export async function fetchBackupStatus(): Promise<BackupStatus> {
	const r = await apiClient.get<DataResponse<BackupStatus>>('/api/v1/admin/backup-status');
	return r.data.data;
}

// ---- /admin/build-status ----
// Snapshot generated by collect-build-status.sh cron (every 5 min)
// and read by lumid_identity from /var/lib/lumid-build-state/.

export interface BuildService {
	service: string;
	container: string;
	container_status: string;
	container_started: string;
	image: string;
	image_id: string;
	image_created: string;
	image_size: string;
	last_built_sha: string;
	last_built_at: string;
	ghcr_digest: string;
	local_digest: string;
	update_pending: 'true' | 'false' | 'unknown';
	restart_pending: boolean;
}

export interface BuildStatus {
	services: BuildService[];
	generated_at: string;
	snapshot_age: number;       // minutes since collection; -1 if no snapshot yet
	note?: string;
}

export async function fetchBuildStatus(): Promise<BuildStatus> {
	const r = await apiClient.get<DataResponse<BuildStatus>>('/api/v1/admin/build-status');
	return r.data.data;
}

// ---- /admin/oauth-clients (super_admin only) ----

export interface OAuthClient {
	client_id: string;
	name: string;
	is_public: boolean;
	grant_types: string[];
	allowed_scopes: string[];
	redirect_uris: string[];
	created_at: string;
}

export interface OAuthClientsResp {
	clients: OAuthClient[];
	total: number;
}

export async function fetchOAuthClients(): Promise<OAuthClientsResp> {
	const r = await apiClient.get<DataResponse<OAuthClientsResp>>(
		'/api/v1/admin/oauth-clients',
	);
	return r.data.data;
}

// ── /admin/loops ───────────────────────────────────────────────────

export interface LoopStep {
	id: string;
	skill: string;
	knowledge_agent?: string;
}

export interface LoopProposal {
	strategy?: string;
	symbol?: string;
	direction?: string;
	size_pct_nav?: number;
}

export interface LoopOutcome {
	alpha_pp?: number;
	benchmark?: string;
	sharpe?: number;
	max_dd?: number;
	insight_head?: string;
	last_proposal?: LoopProposal;
}

export interface StrategyState {
	name: string;
	lifecycle_stage?: 'smoke_test' | 'explore' | 'paper' | 'semi' | 'live' | 'retired' | string;
	cycle_count?: number;
	recent_sharpe?: number;
	lifetime_pnl?: number;
}

export interface LoopRow {
	app: string;
	loop: string;
	schedule: string;
	declared_in: string;
	last_run_ts: number;
	last_ok?: boolean | null;
	consecutive_failures: number;
	last_duration_s: number;
	status: 'ok' | 'never' | 'failing' | 'stale' | 'manual';
	// Detail fields populated inline so a row expand needs no second fetch:
	description?: string;
	primary_role?: string;
	knowledge_agent?: string;
	mode?: string;
	skills?: string[];
	steps?: LoopStep[];
	datasets?: string[];
	goal_primary?: string;
	goal_tracked?: string[];
	latest_cycle_dir?: string;
	latest_cycle_ts?: string;
	// Failing-loop diagnostics — only present when last_ok=false. The
	// dashboard renders these in the expanded row.
	last_errors?: LoopErrorRow[];
	last_journal?: string;
	// Engine pattern (Pattern A or B). Pattern A = runner_steps;
	// Pattern B = command (engine_module names the verb).
	engine?: 'runner_steps' | 'command';
	engine_module?: string;
	skills_invoked?: string[];
	// Cycle outcome — hydrated from score.json/insight.md/proposal.json
	outcome?: LoopOutcome;
}

export interface LoopErrorRow {
	step?: string;
	skill?: string;
	error: string;
}

// Per-app git status — one entry per unique app, parallel to loops[].
// Pivot point for "git status per repo" on the dashboard.
export interface AppGitStatus {
	app: string;
	version?: string;
	kind?: string;
	published: boolean;
	published_slug?: string;
	local_has_git: boolean;
	local_dirty_count: number;
	local_dirty_example?: string;
	local_ahead_origin?: number;
	local_behind_origin?: number;
	local_head?: string;
	local_branch?: string;
	remote_head?: string;
	status: 'in_sync' | 'dirty' | 'ahead' | 'behind' | 'drift' | 'unpublished' | 'no_git';
	strategies?: StrategyState[];
}

export interface LoopsResp {
	loops: LoopRow[];
	apps?: AppGitStatus[];
	summary: { ok: number; never: number; failing: number; stale: number; manual: number };
	scheduler_daemon: 'running' | 'not_installed';
	operator_home: string;
	generated_at: string;
}

// Codebase-repo status — one entry per source-tree git repo under /proj.
// Distinct from xpio AppGitStatus: those are app *bundles* (dropped into
// ~/.xp/apps/), this is the platform's own checkouts.
export interface CodebaseRepo {
	path: string;
	name: string;
	group?: string;
	branch?: string;
	head_short_sha?: string;
	head_subject?: string;
	head_author?: string;
	head_date?: string;
	dirty_count: number;
	dirty_example?: string;
	untracked_count: number;
	ahead_origin?: number;
	behind_origin?: number;
	has_upstream: boolean;
	deprecated?: boolean;
	status: 'clean' | 'dirty' | 'ahead' | 'behind' | 'diverged' | 'no_upstream' | 'detached' | 'no_git';
}

export interface CodebaseReposResp {
	root: string;
	repos: CodebaseRepo[];
	summary: Record<string, number>;
	generated_at: string;
	warning?: string;
}

export async function fetchCodebaseRepos(): Promise<CodebaseReposResp> {
	const r = await apiClient.get<DataResponse<CodebaseReposResp>>('/api/v1/admin/codebase-repos');
	return r.data.data;
}

export async function fetchLoops(): Promise<LoopsResp> {
	const r = await apiClient.get<DataResponse<LoopsResp>>('/api/v1/admin/loops');
	return r.data.data;
}

// Phase D follow-up — /admin/tenants returns per-user operational snapshot.
export interface TenantRow {
	sub: string;
	email: string;
	role: string;
	created_at: string;
	apps: number;
	app_names?: string[];
	storage_mb: number;
	cycles_today: number;
	llm_tokens_today: number;
	gmail_today: number;
	last_cycle_ts?: string;
}
export interface TenantsResp {
	tenants: TenantRow[];
	count: number;
	as_of: string;
}
export async function fetchTenants(): Promise<TenantsResp> {
	const r = await apiClient.get<DataResponse<TenantsResp>>('/api/v1/admin/tenants');
	return r.data.data;
}

// ---- /admin/claude-quota (super_admin only) ----

export interface ClaudeQuotaLimit {
	kind: string;
	group: string;
	percent: number;
	severity: string;
	resets_at: string;
	is_active: boolean;
}

export interface ClaudeQuotaAccount {
	email: string;
	ts: string;
	five_hour_pct: number;
	seven_day_pct: number;
	five_hour_reset: string;
	seven_day_reset: string;
	severity: 'normal' | 'warning' | 'critical';
	stale?: boolean;
	error?: string;
	limits?: ClaudeQuotaLimit[];
}

export interface ClaudeQuotaResp {
	accounts: ClaudeQuotaAccount[];
	count: number;
}

export async function fetchClaudeQuota(): Promise<ClaudeQuotaResp> {
	const r = await apiClient.get<DataResponse<ClaudeQuotaResp>>('/api/v1/admin/claude-quota');
	return r.data.data;
}

export interface AdminClaudeTokenResult {
	email: string;
	valid: boolean;
	stored: boolean;
	upstream_status: number;
	reason: string;
}

export async function adminAddClaudeToken(email: string, token: string, app?: string): Promise<AdminClaudeTokenResult> {
	const r = await apiClient.post<DataResponse<AdminClaudeTokenResult>>('/api/v1/admin/claude-token', { email, token, app });
	return r.data.data;
}

// ---- /api/v1/admin/users ----

export interface AdminUserRow {
	id: string;
	email: string;
	email_verified: boolean;
	name?: string;
	role: string;
	status: string;
	created_at: string;
	updated_at: string;
	active_token_count: number;
	last_login_at?: string;
}

export interface AdminUsersResp {
	users: AdminUserRow[];
	total: number;
	page: number;
	page_size: number;
}

export async function fetchAdminUsers(page = 1, pageSize = 50, status = 'all'): Promise<AdminUsersResp> {
	const r = await apiClient.get<DataResponse<AdminUsersResp>>('/api/v1/admin/users', {
		params: { page, page_size: pageSize, status },
	});
	return r.data.data;
}

// ---- /api/v1/cluster/clusters ----

export interface ClusterRow {
	id: string;
	name: string;
	region?: string;
	status: string;
	owner_user_id: string;
	created_at: string;
	updated_at: string;
}

export interface ClusterListResp {
	clusters: ClusterRow[];
	total: number;
}

export async function fetchClusterList(): Promise<ClusterListResp> {
	const r = await apiClient.get<DataResponse<ClusterListResp>>('/api/v1/cluster/clusters', {
		params: { page_size: 100 },
	});
	return r.data.data;
}
