// Super-admin dashboard API. Hits lumid_identity's /api/v1/admin/*
// surface introduced in P3.1. Same-origin from lum.id, so the
// lm_session cookie + the SuperAdminGuard at the route level is the
// only auth — no scoped bearer needed.

import apiClient from './client';
import type { DataResponse } from './types';

// ---- /admin/auth-stats ----

export interface AuthStatsBucket {
	total: number;
	failed: number;
}

export interface AuthStatsHourly {
	hour: string;
	total: number;
	failed: number;
}

export interface AuthStats {
	window: string;
	generated_at: string;
	login: AuthStatsBucket;
	oauth: AuthStatsBucket;
	hourly: AuthStatsHourly[];
}

export async function fetchAuthStats(): Promise<AuthStats> {
	const r = await apiClient.get<DataResponse<AuthStats>>('/api/v1/admin/auth-stats');
	return r.data.data;
}

// ---- /admin/qa-summary ----

export interface QASummary {
	strategies: { total: number; active: number };
	competitions: { total: number; ongoing: number; upcoming: number };
	trades_24h: { count: number };
	generated_at: string;
}

export async function fetchQASummary(): Promise<QASummary> {
	const r = await apiClient.get<DataResponse<QASummary>>('/api/v1/admin/qa-summary');
	return r.data.data;
}

// ---- /admin/cert-expiry ----

export interface CertRow {
	domain: string;
	expires_at: string;
	days_left: number;
}

export interface CertExpiry {
	certificates: CertRow[];
	checked_at: string;
}

export async function fetchCertExpiry(): Promise<CertExpiry> {
	const r = await apiClient.get<DataResponse<CertExpiry>>('/api/v1/admin/cert-expiry');
	return r.data.data;
}

// ---- /admin/backup-status ----

export interface BackupJob {
	job: string;
	last_run: string;
	age_hours: number;
	healthy: boolean;
}

export interface BackupStatus {
	jobs: BackupJob[];
	verify: { healthy: boolean; last_run?: string };
	checked_at: string;
}

export async function fetchBackupStatus(): Promise<BackupStatus> {
	const r = await apiClient.get<DataResponse<BackupStatus>>('/api/v1/admin/backup-status');
	return r.data.data;
}

// ---- /admin/build-status ----
// Snapshot generated by collect-build-status.sh cron (every 5 min)
// and read by lumid_identity from /var/lib/lumid-build-state/.

export interface BuildService {
	service: string;
	container: string;
	container_status: string;
	container_started: string;
	image: string;
	image_id: string;
	image_created: string;
	image_size: string;
	last_built_sha: string;
	last_built_at: string;
	ghcr_digest: string;
	local_digest: string;
	update_pending: 'true' | 'false' | 'unknown';
	restart_pending: boolean;
}

export interface BuildStatus {
	services: BuildService[];
	generated_at: string;
	snapshot_age: number;       // minutes since collection; -1 if no snapshot yet
	note?: string;
}

export async function fetchBuildStatus(): Promise<BuildStatus> {
	const r = await apiClient.get<DataResponse<BuildStatus>>('/api/v1/admin/build-status');
	return r.data.data;
}

// ---- /admin/oauth-clients (super_admin only) ----

export interface OAuthClient {
	client_id: string;
	name: string;
	is_public: boolean;
	grant_types: string[];
	allowed_scopes: string[];
	redirect_uris: string[];
	created_at: string;
}

export interface OAuthClientsResp {
	clients: OAuthClient[];
	total: number;
}

export async function fetchOAuthClients(): Promise<OAuthClientsResp> {
	const r = await apiClient.get<DataResponse<OAuthClientsResp>>(
		'/api/v1/admin/oauth-clients',
	);
	return r.data.data;
}

// ── /admin/loops ───────────────────────────────────────────────────

export interface LoopStep {
	id: string;
	skill: string;
	knowledge_agent?: string;
}

export interface LoopProposal {
	strategy?: string;
	symbol?: string;
	direction?: string;
	size_pct_nav?: number;
}

export interface LoopOutcome {
	alpha_pp?: number;
	benchmark?: string;
	sharpe?: number;
	max_dd?: number;
	insight_head?: string;
	last_proposal?: LoopProposal;
}

export interface StrategyState {
	name: string;
	lifecycle_stage?: 'smoke_test' | 'explore' | 'paper' | 'semi' | 'live' | 'retired' | string;
	cycle_count?: number;
	recent_sharpe?: number;
	lifetime_pnl?: number;
}

export interface LoopRow {
	app: string;
	loop: string;
	schedule: string;
	declared_in: string;
	last_run_ts: number;
	last_ok?: boolean | null;
	consecutive_failures: number;
	last_duration_s: number;
	status: 'ok' | 'never' | 'failing' | 'stale' | 'manual';
	// Detail fields populated inline so a row expand needs no second fetch:
	description?: string;
	primary_role?: string;
	knowledge_agent?: string;
	mode?: string;
	skills?: string[];
	steps?: LoopStep[];
	datasets?: string[];
	goal_primary?: string;
	goal_tracked?: string[];
	latest_cycle_dir?: string;
	latest_cycle_ts?: string;
	// Failing-loop diagnostics — only present when last_ok=false. The
	// dashboard renders these in the expanded row.
	last_errors?: LoopErrorRow[];
	last_journal?: string;
	// Engine pattern (Pattern A or B). Pattern A = runner_steps;
	// Pattern B = command (engine_module names the verb).
	engine?: 'runner_steps' | 'command';
	engine_module?: string;
	skills_invoked?: string[];
	// Cycle outcome — hydrated from score.json/insight.md/proposal.json
	outcome?: LoopOutcome;
}

export interface LoopErrorRow {
	step?: string;
	skill?: string;
	error: string;
}

// Per-app git status — one entry per unique app, parallel to loops[].
// Pivot point for "git status per repo" on the dashboard.
export interface AppGitStatus {
	app: string;
	version?: string;
	kind?: string;
	published: boolean;
	published_slug?: string;
	local_has_git: boolean;
	local_dirty_count: number;
	local_dirty_example?: string;
	local_ahead_origin?: number;
	local_behind_origin?: number;
	local_head?: string;
	local_branch?: string;
	remote_head?: string;
	status: 'in_sync' | 'dirty' | 'ahead' | 'behind' | 'drift' | 'unpublished' | 'no_git';
	strategies?: StrategyState[];
}

export interface LoopsResp {
	loops: LoopRow[];
	apps?: AppGitStatus[];
	summary: { ok: number; never: number; failing: number; stale: number; manual: number };
	scheduler_daemon: 'running' | 'not_installed';
	operator_home: string;
	generated_at: string;
}

// Codebase-repo status — one entry per source-tree git repo under /proj.
// Distinct from xpio AppGitStatus: those are app *bundles* (dropped into
// ~/.xp/apps/), this is the platform's own checkouts.
export interface CodebaseRepo {
	path: string;
	name: string;
	group?: string;
	branch?: string;
	head_short_sha?: string;
	head_subject?: string;
	head_author?: string;
	head_date?: string;
	dirty_count: number;
	dirty_example?: string;
	untracked_count: number;
	ahead_origin?: number;
	behind_origin?: number;
	has_upstream: boolean;
	deprecated?: boolean;
	status: 'clean' | 'dirty' | 'ahead' | 'behind' | 'diverged' | 'no_upstream' | 'detached' | 'no_git';
}

export interface CodebaseReposResp {
	root: string;
	repos: CodebaseRepo[];
	summary: Record<string, number>;
	generated_at: string;
	warning?: string;
}

export async function fetchCodebaseRepos(): Promise<CodebaseReposResp> {
	const r = await apiClient.get<DataResponse<CodebaseReposResp>>('/api/v1/admin/codebase-repos');
	return r.data.data;
}

export async function fetchLoops(): Promise<LoopsResp> {
	const r = await apiClient.get<DataResponse<LoopsResp>>('/api/v1/admin/loops');
	return r.data.data;
}

// Phase D follow-up — /admin/tenants returns per-user operational snapshot.
export interface TenantRow {
	sub: string;
	email: string;
	role: string;
	created_at: string;
	apps: number;
	app_names?: string[];
	storage_mb: number;
	cycles_today: number;
	llm_tokens_today: number;
	gmail_today: number;
	last_cycle_ts?: string;
}
export interface TenantsResp {
	tenants: TenantRow[];
	count: number;
	as_of: string;
}
export async function fetchTenants(): Promise<TenantsResp> {
	const r = await apiClient.get<DataResponse<TenantsResp>>('/api/v1/admin/tenants');
	return r.data.data;
}

// ---- /admin/claude-quota (super_admin only) ----

export interface ClaudeQuotaLimit {
	kind: string;
	group: string;
	percent: number;
	severity: string;
	resets_at: string;
	is_active: boolean;
}

export interface ClaudeQuotaAccount {
	email: string;
	ts: string;
	five_hour_pct: number;
	seven_day_pct: number;
	five_hour_reset: string;
	seven_day_reset: string;
	severity: 'normal' | 'warning' | 'critical';
	stale?: boolean;
	error?: string;
	limits?: ClaudeQuotaLimit[];
	// Quarantine: the token family was revoked (invalid_grant) — the backend
	// stops retrying it; recovery is a re-add with a fresh `claude auth login`.
	revoked?: boolean;
	revoke_reason?: string;
	// Label: set when this account belongs to a field box (e.g. "dublin") —
	// its Messages API + token-refresh traffic routes through that box's own
	// relay instead of the default direct path. Empty for a normal account.
	label?: string;
}

export interface ClaudeQuotaResp {
	accounts: ClaudeQuotaAccount[];
	count: number;
}

export async function fetchClaudeQuota(): Promise<ClaudeQuotaResp> {
	const r = await apiClient.get<DataResponse<ClaudeQuotaResp>>('/api/v1/admin/claude-quota');
	return r.data.data;
}

export interface ClaudeUserModelUsage {
	tokens_7d: number;
	cost_cents_7d: number;
}

export interface ClaudeUserUsage {
	email: string;
	five_hour_tokens: number;
	seven_day_tokens: number;
	five_hour_pct: number;
	seven_day_pct: number;
	// Claude-only weighted draw + pct — the bars reflect POOLED CLAUDE ONLY
	// (the gate exempts deepseek/on-prem from the cap), so OpenRouter/on-prem
	// usage must not draw against the Claude budget on-screen.
	claude_five_hour_tokens?: number;
	claude_seven_day_tokens?: number;
	claude_five_hour_pct?: number;
	claude_seven_day_pct?: number;
	cost_cents_7d: number;
	requests_7d: number;
	last_ts: string;
	five_hour_reset?: string;
	seven_day_reset?: string;
	models?: Record<string, ClaudeUserModelUsage>;
	// Provider-grouped 7d subtotals: "claude" | "openrouter" | "onprem" →
	// {tokens_7d, cost_cents_7d}.
	providers?: Record<string, ClaudeUserModelUsage>;
	// RAW 7d token totals exactly as Anthropic reported them — the true token
	// count, distinct from the weighted five_hour_tokens/seven_day_tokens quota
	// unit (cache reads at a tenth, model by price ratio).
	raw_input_tokens_7d?: number;
	raw_output_tokens_7d?: number;
	raw_cache_read_tokens_7d?: number;
	raw_cache_creation_tokens_7d?: number;
	raw_total_tokens_7d?: number;
}

export interface ClaudeUserUsageResp {
	users: ClaudeUserUsage[];
	five_hour_tokens: number; // per-user cap for the SHORT window
	seven_day_tokens: number; // per-user cap
	// Length of the short window, e.g. "4h". Server-supplied because it is
	// env-tunable (LUMID_QUOTA_CLAUDE_SHORT_WINDOW) and stopped being 5h on
	// 2026-08-11 — a hardcoded label silently lies the next time it moves.
	// The five_hour_* keys keep their historical names for wire compatibility.
	short_window_label?: string;
}

export async function fetchClaudeUserUsage(): Promise<ClaudeUserUsageResp> {
	const r = await apiClient.get<DataResponse<ClaudeUserUsageResp>>('/api/v1/admin/claude-user-usage');
	return r.data.data;
}

// ── OpenRouter balance ───────────────────────────────────────────────
// Metered pay-per-use side of the pool. The key never leaves the server; this
// endpoint returns the account credit (GET /api/v1/credits → total_credits /
// total_usage in USD). balance_usd = total_credits - total_usage. available:false
// degrades gracefully (missing key / unreachable) so the panel blanks instead
// of erroring.
export interface OpenRouterBalanceResp {
	available: boolean;
	balance_usd: number;
	total_credits: number;
	usage_usd: number;
	error?: string;
}

export async function fetchOpenRouterBalance(): Promise<OpenRouterBalanceResp> {
	const r = await apiClient.get<DataResponse<OpenRouterBalanceResp>>('/api/v1/admin/openrouter-balance');
	return r.data.data;
}

// ── Claude session transcripts (lum.id/claude recording) ──────────────
export interface ClaudeSessionCard {
	conv_key: string;
	user_sub?: string;
	user_email?: string;
	account: string;
	model: string;
	title: string;
	turn_count: number;
	input_tokens: number;
	output_tokens: number;
	tool_use_count: number;
	first_ts: string;
	last_ts: string;
}

export interface ClaudeSessionTurn {
	turn_index: number;
	ts: string;
	model: string;
	endpoint: string;
	stream: boolean;
	input_tokens: number;
	output_tokens: number;
	tool_use_count: number;
	duration_ms: number;
	truncated: boolean;
	request_meta: unknown; // {system, tools, max_tokens, ...} minus messages
	new_messages: unknown; // messages[] added this turn
	response: unknown;     // full response (assembled JSON or raw SSE string)
}

export interface ClaudeSessionDetail {
	session: ClaudeSessionCard;
	turns: ClaudeSessionTurn[];
	// Pagination. The endpoint returns the NEWEST window of turns, not the whole
	// transcript: a 517-turn session was a 72 MB / 48s response that blew the
	// 30s client timeout. Walk backwards with ?before=<oldest_turn_index>.
	total_turns?: number;
	returned?: number;
	oldest_turn_index?: number;
	has_more?: boolean;
	remaining?: number;
}

// admin=true → super_admin all-users view; else owner's own sessions.
export async function fetchClaudeSessions(admin = false): Promise<ClaudeSessionCard[]> {
	const path = admin ? '/api/v1/admin/claude-sessions' : '/api/v1/me/claude-sessions';
	const r = await apiClient.get<DataResponse<{ sessions: ClaudeSessionCard[] }>>(path);
	return r.data.data.sessions ?? [];
}

export async function fetchClaudeSession(
	convKey: string,
	admin = false,
	opts: { limit?: number; before?: number } = {},
): Promise<ClaudeSessionDetail> {
	const base = admin ? '/api/v1/admin/claude-sessions' : '/api/v1/me/claude-sessions';
	const qs = new URLSearchParams();
	if (opts.limit) qs.set('limit', String(opts.limit));
	if (opts.before !== undefined) qs.set('before', String(opts.before));
	const suffix = qs.toString() ? `?${qs}` : '';
	const r = await apiClient.get<DataResponse<ClaudeSessionDetail>>(`${base}/${convKey}${suffix}`);
	return r.data.data;
}

export async function deleteClaudeSession(convKey: string, admin = false): Promise<void> {
	const base = admin ? '/api/v1/admin/claude-sessions' : '/api/v1/me/claude-sessions';
	await apiClient.delete(`${base}/${convKey}`);
}

export async function fetchClaudeRecording(): Promise<boolean> {
	const r = await apiClient.get<DataResponse<{ enabled: boolean }>>('/api/v1/me/claude-recording');
	return r.data.data.enabled;
}

export async function setClaudeRecording(enabled: boolean): Promise<boolean> {
	const r = await apiClient.post<DataResponse<{ enabled: boolean }>>('/api/v1/me/claude-recording', { enabled });
	return r.data.data.enabled;
}

export interface AdminClaudeTokenResult {
	email: string;
	valid: boolean;
	stored: boolean;
	upstream_status: number;
	reason: string;
	label?: string;
}

export async function adminAddClaudeToken(
	email: string,
	token: string,
	refreshToken?: string,
	label?: string,
): Promise<AdminClaudeTokenResult> {
	const body: Record<string, string> = { email, token };
	if (refreshToken) body.refresh_token = refreshToken;
	if (label) body.label = label;
	const r = await apiClient.post<DataResponse<AdminClaudeTokenResult>>('/api/v1/admin/claude-token', body);
	return r.data.data;
}

export async function adminDeleteClaudeToken(email: string): Promise<void> {
	await apiClient.delete(`/api/v1/admin/claude-token/${encodeURIComponent(email)}`);
}

/**
 * Reset ONE user's pooled-quota clock. super_admin only (the route is
 * RequireSuperAdmin server-side; the page is gated too, so this is defence in
 * depth rather than the only check).
 *
 * `window` maps to the server's vocabulary: 'short' is the 4h window, 'weekly'
 * the 7d one. The server EXPIRES the anchor rather than deleting the row or
 * stamping it to now — an expired anchor is the natural "no window open" state,
 * so the user reads zero and a fresh window opens on their next charge instead
 * of a 4h clock ticking down while they are not working.
 *
 * Takes a REQUIRED email. The fleet-wide form is a separate function below, so
 * "reset one user" can never become "reset everyone" by passing undefined.
 */
export async function adminResetClaudePoolWindow(
	email: string,
	window: 'short' | 'weekly',
): Promise<void> {
	await apiClient.post('/api/v1/admin/claude-pool/reset-window', { email, window });
}

/**
 * Reset the pooled-quota clock for EVERY user. super_admin only.
 *
 * Separate function rather than an optional email on the one above: an omitted
 * argument is exactly how a single-user reset silently becomes a fleet-wide one.
 * Making it its own call means the blast radius is visible at the call site and
 * cannot be reached by accident.
 *
 * This is what the endpoint was originally built for — on 2026-08-11 the cap moved
 * 4M/5h -> 2M/4h and every anchor in the table had been opened under the old
 * policy, so users who had spent 3M were instantly over the new ceiling through no
 * action of their own. A fleet reset hands everyone a clean window under the new
 * rules. Outside a retune like that, prefer the per-user button.
 */
export async function adminResetClaudePoolWindowAll(
	window: 'short' | 'weekly' | 'both',
): Promise<{ reset: number; window: string }> {
	// Returns the row count on purpose. The handler documents that it "always
	// reports the row count and which window moved, so a pool-wide reset is
	// never silent" — dropping it here would defeat that from the one surface
	// where the reset is actually fired. The per-user form stays void: there
	// the scope is the row you clicked.
	const r = await apiClient.post<DataResponse<{ reset: number; window: string }>>(
		'/api/v1/admin/claude-pool/reset-window',
		{ window },
	);
	return { reset: r.data.data.reset ?? 0, window: r.data.data.window || window };
}

// ---- /api/v1/admin/users ----

export interface AdminUserRow {
	id: string;
	email: string;
	email_verified: boolean;
	name?: string;
	role: string;
	status: string;
	created_at: string;
	updated_at: string;
	active_token_count: number;
	last_login_at?: string;
}

export interface AdminUsersResp {
	users: AdminUserRow[];
	total: number;
	page: number;
	page_size: number;
}

export async function fetchAdminUsers(page = 1, pageSize = 50, status = 'all'): Promise<AdminUsersResp> {
	const r = await apiClient.get<DataResponse<AdminUsersResp>>('/api/v1/admin/users', {
		params: { page, page_size: pageSize, status },
	});
	return r.data.data;
}

// ---- /api/v1/cluster/clusters ----

export interface ClusterRow {
	id: string;
	name: string;
	region?: string;
	status: string;
	owner_user_id: string;
	created_at: string;
	updated_at: string;
}

export interface ClusterListResp {
	clusters: ClusterRow[];
	total: number;
}

export async function fetchClusterList(): Promise<ClusterListResp> {
	const r = await apiClient.get<DataResponse<ClusterListResp>>('/api/v1/cluster/clusters', {
		params: { page_size: 100 },
	});
	return r.data.data;
}

// ── per-field-box traffic breakdown (/code panel) ──────────────────────────

export interface ClaudeFieldBoxRow {
	/** "" = dispatched DIRECT from the cluster (unlabelled account). */
	field_box: string;
	/**
	 * Users ASSIGNED to this box's pooled account right now (current state,
	 * not windowed). The balancing number — what a rebalance moves.
	 */
	homed_users: number;
	/**
	 * Distinct users whose turns took this box in the window. Overlaps between
	 * boxes (leases rotate) and undercounts users who opted out of transcript
	 * recording, so it is traffic evidence, not placement.
	 */
	active_users: number;
	turns: number;
	via_relay: number;
	not_via_relay: number;
	request_bytes: number;
	response_bytes: number;
	input_tokens: number;
	output_tokens: number;
	last_ts: string;
	/**
	 * The anthropic-sdk-typescript fingerprint claude-proxy is currently
	 * attaching to this box's egress. Absent for the "(direct)" row and for
	 * any homed-but-unconfigured label — see identity's
	 * claude_field_fingerprint.go.
	 */
	fingerprint?: {
		user_agent: string;
		os: string;
		arch: string;
		runtime: string;
		package_version: string;
		/** true = pinned via LUMID_CLAUDE_FIELD_RELAY_FINGERPRINTS; never rotates. */
		override: boolean;
		/** absent/empty when override is true. */
		rotates_at?: string;
	};
}

export interface ClaudeFieldBoxResp {
	window_hours: number;
	/** When via_relay reporting began; totals.degraded_turns only covers turns after it. */
	signal_since: string | null;
	boxes: ClaudeFieldBoxRow[];
	totals: {
		/** Users assigned across all boxes. Sums cleanly — one account per user. */
		homed_users: number;
		/** Distinct users seen in the window — NOT the sum of boxes[].active_users,
		 *  since one user can span boxes when a lease rotates. */
		active_users: number;
		turns: number;
		request_bytes: number;
		response_bytes: number;
		/** Labelled turns that did NOT take the relay hop. >0 = silent degradation. */
		degraded_turns: number;
	};
}

export async function fetchClaudeFieldBoxes(hours = 24): Promise<ClaudeFieldBoxResp> {
	const r = await apiClient.get<DataResponse<ClaudeFieldBoxResp>>(
		`/api/v1/admin/claude-field-boxes?hours=${hours}`,
	);
	return r.data.data;
}
